Feature: Table Filter

  Scenario:
    Given I am on "collection/tablefilter.php"
    Then I should see "Australia"
    Then I click filter column name "atk_fp_country__name"
    When I fill in "value" with "united kingdom"
    Then I press button "Set"
    Then I should not see "Australia"
    Then I should see "United Kingdom"
    Then I click filter column name "atk_fp_country__phonecode"
    When I fill field using "//div.popup[5]//input[@name='value']" with "44"
    Then I press button using selector "//div.popup[5]//div[text()='Set']"
    Then I should see "United Kingdom"
    Then I click filter column name "atk_fp_country__phonecode"
    When I fill field using "//div.popup[5]//input[@name='value']" with "4"
    Then I press button using selector "//div.popup[5]//div[text()='Set']"
    Then I should not see "United Kingdom"
    Then I should see "No records"
    Then I click filter column name "atk_fp_country__phonecode"
    Then I press button using selector "//div.popup[5]//div[text()='Clear']"
    Then I should not see "No records"
    Then I should see "United Kingdom"
    Then I press menu button "Clear Filters" using selector ".ui.menu.atk-grid-menu"
    Then I should not see "United Kingdom"
    Then I should see "Australia"
