Feature: Multiline

  Scenario:
    Given I am on "form-control/multiline.php"
    When I fill field using "div[name=-atk_fp_multiline_item__qty] input" with "0"
    Then the "div[name=-atk_fp_multiline_item__total_sql]" element should contain "0"
    Then the "div[name=-atk_fp_multiline_item__total_php]" element should contain "0"
    When I fill field using "div[name=-atk_fp_multiline_item__qty] input" with "4"
    When I fill field using "div[name=-atk_fp_multiline_item__box] input" with "67"
    Then the "div[name=-atk_fp_multiline_item__total_sql]" element should contain "268"
    Then the "div[name=-atk_fp_multiline_item__total_php]" element should contain "268"
    When I select "Argentina" in lookup "//table//tr[1]//div.text[parent::div[@name='-atk_fp_multiline_item__country_id']]"
    When I press button "Save"
    Then Toast display should contain text "\"atk_fp_multiline_item__box\": \"67\", \"atk_fp_multiline_item__total_sql\": \"268\" }"
    Then Toast display should contain text "\"atk_fp_multiline_item__country_id\": \"10\", \"atk_fp_multiline_item__qty\": \"4\","
    Then Toast display should contain text "\"atk_fp_multiline_item__country_id\": \"223\", \"atk_fp_multiline_item__qty\": \"2\","

  Scenario: add row
    When I click using selector "//tfoot//button[i.plus.icon]"
    Then I should not see "Must not be empty"
    When I press button "Save"
    Then I should see "Must not be empty"
    When I fill field using "//tr[3]//div[@name='-atk_fp_multiline_item__item']/input" with "Paper"
    When I fill field using "//tr[3]//div[@name='-atk_fp_multiline_item__qty']/input" with "3"
    When I fill field using "//tr[3]//div[@name='-atk_fp_multiline_item__box']/input" with "5"
    Then I check if text in "//tr[3]//div[@name='-atk_fp_multiline_item__total_sql']" match text "15"
    Then I check if text in "//tr[3]//div[@name='-atk_fp_multiline_item__total_php']" match text "15"
    When I press button "Save"
    Then Toast display should contain text "\"atk_fp_multiline_item__box\": \"5\", \"atk_fp_multiline_item__total_sql\": \"15\" } ]"
    Then I should not see "Must not be empty"

  Scenario: delete row
    When I click using selector "//tr[3]//input[@type='checkbox']"
    When I click using selector "//tfoot//button[i.trash.icon]"
    When I press button "Save"
    Then Toast display should contain text "\"atk_fp_multiline_item__box\": \"100\", \"atk_fp_multiline_item__total_sql\": \"200\" } ]"

  Scenario: delete all rows
    When I click using selector "//thead//input[@type='checkbox']"
    When I click using selector "//tfoot//button[i.trash.icon]"
    When I press button "Save"
    Then Toast display should contain text "[]"

  Scenario: dropdown enum
    Given I am on "_unit-test/multiline-enum.php"
    When I click using selector "//tfoot//button[i.plus.icon]"
    When I check if text in "//div.text[parent::div[@name='-age0']]" match text ""
    When I check if text in "//div.text[parent::div[@name='-age1']]" match text "Child"
    When I check if text in "//div.text[parent::div[@name='-age2']]" match text "Adult"
    When I check if text in "//div.text[parent::div[@name='-age3']]" match text "3\u{00a0}000"
    When I check if text in "textarea[name=-text]" match text "a\nb"
    When I press button "Save"
    Then Toast display should contain text "[ { \"id\": null, \"age0\": null, \"age1\": 1, \"age2\": 2000, \"age3\": 3000, \"text\": \"a\\nb\" } ]"

    When I select "Child" in lookup "//div.text[parent::div[@name='-age0']]"
    When I select "Adult" in lookup "//div.text[parent::div[@name='-age1']]"
    When I select "" in lookup "//div.text[parent::div[@name='-age2']]"
    When I select "" in lookup "//div.text[parent::div[@name='-age3']]"
    When I fill field using "textarea[name=-text]" with "a\n b"
    When I check if text in "//div.text[parent::div[@name='-age0']]" match text "Child"
    When I check if text in "//div.text[parent::div[@name='-age1']]" match text "Adult"
    When I check if text in "//div.text[parent::div[@name='-age2']]" match text ""
    When I check if text in "//div.text[parent::div[@name='-age3']]" match text ""
    When I check if text in "textarea[name=-text]" match text "a\n b"
    When I press button "Save"
    Then Toast display should contain text "[ { \"id\": null, \"age0\": 1, \"age1\": 2000, \"age2\": null, \"age3\": null, \"text\": \"a\\n b\" } ]"

  Scenario: contained - Form
    Given I am on "form-control/multiline-containsmany-single.php"
    # 'ce0a190b1901b807' = substr(md5('multiline_delivery'), 0, 16)
    When I fill in "atk_fp_ce0a190b1901b807__name" with "Delivery Foo"
    When I click using selector "//div.field[label[text()='Item']]//tfoot//button[i.plus.icon]"
    Then Element "//div.field[label[text()='Item']]//tfoot//button[i.plus.icon]" attribute "class" should contain text "disabled"
    When I fill field using "div[name=-atk_fp_tbl__item] input" with "Melon"
    When I select "Argentina" in lookup "//div.text[parent::div[@name='-atk_fp_tbl__country_id']]"
    When I fill field using "div[name=-atk_fp_tbl__qty] input" with "5"
    When I fill field using "div[name=-atk_fp_tbl__box] input" with "6"
    When I press button "Save"
    Then Toast display should contain text "\"atk_fp_ce0a190b1901b807__name\": \"Delivery Foo\","
    Then Toast display should contain text "\"atk_fp_ce0a190b1901b807__item\": { \"atk_afp_tbl__id\": 1, \"atk_afp_tbl__item\": \"Melon\","
    Then Toast display should contain text "\"atk_afp_tbl__country_id\": 10, \"atk_afp_tbl__qty\": 5, \"atk_afp_tbl__box\": 6 }"
    Then Toast display should contain text "\"atk_fp_ce0a190b1901b807__items\": null }"

  Scenario: contained - Crud - with unlocked DB
    Given I am on "form-control/multiline-containsmany.php"
    When I persist DB changes across requests
    When I press button "Add"
    # 'ce0a190b1901b807' = substr(md5('multiline_delivery'), 0, 16)
    When I fill in "atk_fp_ce0a190b1901b807__name" with "Cheetah"
    When I click using selector "//div.field[label[text()='Item']]//tfoot//button[i.plus.icon]"
    When I fill field using "//div.field[label[text()='Item']]//div[@name=\"-atk_fp_tbl__item\"]/input" with "Melon"
    When I select "Argentina" in lookup "//div.field[label[text()='Item']]//div.text[parent::div[@name='-atk_fp_tbl__country_id']]"
    When I fill field using "//div.field[label[text()='Item']]//div[@name=\"-atk_fp_tbl__qty\"]/input" with "5"
    When I fill field using "//div.field[label[text()='Item']]//div[@name=\"-atk_fp_tbl__box\"]/input" with "6"
    When I click using selector "//div.field[label[text()='Items']]//tfoot//button[i.plus.icon]"
    When I fill field using "//div.field[label[text()='Items']]//div[@name=\"-atk_fp_tbl__item\"]/input" with "Pear"
    When I fill field using "//div.field[label[text()='Items']]//div[@name=\"-atk_fp_tbl__qty\"]/input" with "7"
    When I fill field using "//div.field[label[text()='Items']]//div[@name=\"-atk_fp_tbl__box\"]/input" with "8"
    When I press Modal button "Save"
    Then Toast display should contain text "Record has been saved!"
    Then I check if text in "//table//tr[1]/td[1]" match text "Cheetah"
    Then I check if text in "//table//tr[1]/td[2]" match regex "~^\{\"atk_afp_tbl__id\":1,[^{}]*\"atk_afp_tbl__item\":\"Melon\",~"
    Then I check if text in "//table//tr[1]/td[2]" match regex "~\"atk_afp_tbl__country_id\":10[,}]~"
    Then I check if text in "//table//tr[1]/td[2]" match regex "~\"atk_afp_tbl__qty\":5[,}]~"
    Then I check if text in "//table//tr[1]/td[2]" match regex "~\"atk_afp_tbl__box\":6[,}]~"
    Then I check if text in "//table//tr[1]/td[3]" match regex "~^\[\{\"atk_afp_tbl__id\":1,[^{}]*\"atk_afp_tbl__item\":\"Pear\",~"
    Then I check if text in "//table//tr[1]/td[3]" match regex "~\"atk_afp_tbl__country_id\":null~"
    Then I check if text in "//table//tr[1]/td[3]" match regex "~\"atk_afp_tbl__qty\":7[,}]~"
    Then I check if text in "//table//tr[1]/td[3]" match regex "~\"atk_afp_tbl__box\":8[,}]~"

    When I click using selector "//table//tr[1]//i.icon.edit"
    When I fill field using "//div.modal.active//div.field[label[text()='Item']]//div[@name=\"-atk_fp_tbl__qty\"]/input" with "9"
    When I click using selector "//div.modal.active//div.field[label[text()='Items']]//tfoot//button[i.plus.icon]"
    When I fill field using "(//div.modal.active//div.field[label[text()='Items']]//div[@name=\"-atk_fp_tbl__item\"])[2]/input" with "Mango"
    When I fill field using "(//div.modal.active//div.field[label[text()='Items']]//div[@name=\"-atk_fp_tbl__qty\"])[2]/input" with "17"
    When I fill field using "(//div.modal.active//div.field[label[text()='Items']]//div[@name=\"-atk_fp_tbl__box\"])[2]/input" with "18"
    When I press Modal button "Save"
    Then Toast display should contain text "Record has been saved!"
    Then I check if text in "//table//tr[1]/td[2]" match regex "~^\{\"atk_afp_tbl__id\":1,[^{}]*\"atk_afp_tbl__item\":\"Melon\",~"
    Then I check if text in "//table//tr[1]/td[2]" match regex "~\"atk_afp_tbl__country_id\":10[,}]~"
    Then I check if text in "//table//tr[1]/td[2]" match regex "~\"atk_afp_tbl__qty\":9[,}]~"
    Then I check if text in "//table//tr[1]/td[2]" match regex "~\"atk_afp_tbl__box\":6[,}]~"
    Then I check if text in "//table//tr[1]/td[3]" match regex "~^\[\{\"atk_afp_tbl__id\":1,[^{}]*\"atk_afp_tbl__item\":\"Pear\",~"
    Then I check if text in "//table//tr[1]/td[3]" match regex "~\"atk_afp_tbl__country_id\":null~"
    Then I check if text in "//table//tr[1]/td[3]" match regex "~\"atk_afp_tbl__qty\":7[,}]~"
    Then I check if text in "//table//tr[1]/td[3]" match regex "~\"atk_afp_tbl__box\":8[,}]~"
    Then I check if text in "//table//tr[1]/td[3]" match regex "~\{\"atk_afp_tbl__id\":2,[^{}]*\"atk_afp_tbl__item\":\"Mango\",~"

    When I click using selector "//table//tr[1]//i.icon.edit"
    When I click using selector "(//div.modal.active//div.field[label[text()='Items']]//tbody//input[@type=\"checkbox\"])[1]"
    When I click using selector "//div.modal.active//div.field[label[text()='Items']]//tfoot//button[i.trash.icon]"
    When I press Modal button "Save"
    Then Toast display should contain text "Record has been saved!"
    Then I check if text in "//table//tr[1]/td[2]" match regex "~^\{\"atk_afp_tbl__id\":1,[^{}]*\"atk_afp_tbl__item\":\"Melon\",~"
    Then I check if text in "//table//tr[1]/td[3]" match regex "~^\[\{\"atk_afp_tbl__id\":2,[^{}]*\"atk_afp_tbl__item\":\"Mango\",~"

    When I click using selector "//table//tr[1]//i.icon.trash"
    When I press Modal button "Ok"
    Then Toast display should contain text "Record has been deleted!"
    Then I should not see "Cheetah"
