version: "1.0"
stages:
  - clone
  - build
  - push
  - deploy
steps:
  main_clone:
    type: git-clone
    stage: clone
  build:
    type: build
    stage: build
    image_name: atk4/ui
  push:
    type: push
    stage: push
    image_name: atk4/ui
    registry: cfcr
    candidate: "${{build}}"
    tags:
      - "${{CF_BRANCH_TAG_NORMALIZED}}"
      - "${{CF_REVISION}}"


