version: "1.0"
stages:
  - clone
  - build
  - push
  - deploy
steps:
  main_clone:
    type: git-clone
    stage: clone
    repo: atk4/ui
    revision: "${{CF_BRANCH}}"
  build:
    type: build
    stage: build
    image_name: atk4/ui
  push:
    type: push
    stage: push
    image_name: atk4/ui
    registry: cfcr
    candidate: "${{build}}"
    tags:
      - "${{CF_BRANCH_TAG_NORMALIZED}}"
      - "${{CF_REVISION}}"
  deploy:
    image: codefresh/kubectl:1.13.3
    stage: deploy
    commands:
      - echo $CF_KUBECONFIG_PATH
      - kubectl config get-contexts
      - kubectl config use-context atk
      - kubectl get deploymetns -n atk-demo
      - kubectl -n atk-demo set image deployment/atk-demo atk-demo="r.cfcr.io/romaninsh/atk4/ui:${{CF_REVISION}}"

