<?php

namespace atk4\ui\ActionExecutor;

use atk4\core\HookTrait;
use atk4\ui\Exception;
use atk4\ui\jsExpressionable;
use atk4\ui\jsToast;

class Basic extends \atk4\ui\View implements Interface_
{
    use HookTrait;

    /**
     * @var \atk4\data\UserAction\Action
     */
    public $action = null;

    /**
     * @var array
     */
    protected $arguments = [];

    public $description = null;

    /**
     * @var array list of validated arguments
     */
    protected $validArguments = [];

    /**
     * @var jsExpressionable|array jsExpression to return if action was successful, e.g "new jsToast('Tahnk you')"
     */
    protected $jsSuccess = null;

    /**
     * Associate executor with action.
     *
     * @param \atk4\data\UserAction\Action $action
     */
    public function setAction(\atk4\data\UserAction\Generic $action)
    {
        $this->action = $action;
    }

    /**
     * Provide values for named arguments.
     *
     * @param array $arguments
     */
    public function setArguments(array $arguments)
    {
        // TODO: implement mechanism for validating arguments based on definition

        $this->arguments = array_merge($this->arguments, $arguments);
    }

    public function recursiveRender()
    {
        if (!$this->action) {
            throw new \atk4\ui\Exception(['Action is not set. Use setAction()']);
        }

        // check action can be called
        if ($this->action->enabled) {
            $this->initPreview();
        } else {
            $this->add(['Message', 'type'=>'error', 'Action is disabled and cannot be executed']);

            return;
        }

        parent::recursiveRender(); // TODO: Change the autogenerated stub
    }

    /**
     * Check if all argument values have been provided.
     */
    public function hasAllArguments()
    {
        foreach ($this->action->args as $key => $val) {
            if (!isset($this->arguments[$key])) {
                throw new Exception(['Argument is not provided', 'argument'=>$key]);
            }
        }

        return true;
    }

    protected function initPreview()
    {

        // lets make sure that all arguments are supplied
        if (!$this->hasAllArguments()) {
            $this->add(['Message', 'type'=>'error', 'Insufficient arguments']);

            return;
        }

        $this->add(['Header', $this->action->caption, 'subHeader'=>$this->description ?: $this->action->getDescription()]);

        $this->add(['Button', 'Confirm', 'primary'])->on('click', function () {
            return $this->jsExecute();
        });
    }

    /**
     * Will call $action->execute() with the correct arguments.
     */
    public function jsExecute()
    {
        $args = [];

        foreach ($this->action->args as $key => $val) {
            $args[] = $this->arguments[$key];
        }

        $return = $this->action->execute(...$args);

        return $this->hook('afterExecute', [$return]) ?: $this->jsSuccess ?: new jsToast('Success'.(is_string($return) ? (': '.$return) : ''));
    }
}
