version: 2

build:
  os: ubuntu-lts-latest
  tools:
    # https://github.com/readthedocs/readthedocs.org/issues/9719
    python: '3'

python:
  install:
    # https://github.com/readthedocs/readthedocs.org/issues/10806
    - requirements: docs/requirements.txt

sphinx:
  # https://github.com/readthedocs/readthedocs.org/issues/10806
  configuration: docs/conf.py

formats:
  - pdf
  - epub
  - htmlzip
